SELECT TABLE_NAME
,COLUMN_NAME
, DATA_TYPE, 
CASE WHEN DATA_TYPE IN('varchar','nvarchar','char') then CAST(CHARACTER_MAXIMUM_LENGTH AS VARCHAR)
WHEN DATA_TYPE IN('NUMERIC', 'DECIMAL') THEN CAST(NUMERIC_PRECISION AS VARCHAR)+', '+CAST(NUMERIC_SCALE AS VARCHAR)
ELSE NULL END AS 'DATA PRECISION'
FROM INFORMATION_SCHEMA.COLUMNS
WHERE 
     TABLE_NAME = 'employee' --Change to table you want to look at